http://stackoverflow.com/a/7883083/26877


public static void LogExceptions(this Task task)
{
    task.ContinueWith( t =>
    {
         var aggException = t.Exception.Flatten();
         foreach(var exception in aggException.InnerExceptions)
             LogException(exception);
    }, 
    TaskContinuationOptions.OnlyOnFaulted);
}

Task.Factory.StartNew( () => 
   { 
       // Do your work...
   }).LogExceptions();